// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vijosopaqoyvcvqpaakd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpam9zb3BhcW95dmN2cXBhYWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTg0NjgsImV4cCI6MjA2NzM5NDQ2OH0.gbnYvU9-sEKzodTWWC8TTsx-4iO_fN4V7QTRwXbqMAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});